<?php

namespace app\models;

use app\core\Database;
use PDO;

// StaffModel: the EER's single Staff entity — login credentials and academic
// catalog data in one table (replaces the old UserModel + LecturerModel's/
// InstructorModel's underlying `lecturers`/`instructors` tables, which used
// to be disconnected from login). Keyed by `code`, not a surrogate id.
//
// Since migration 016, a row can also be `status = 'pending'`: a self
// registration with no `role`/`academic_rank`/`position` yet, awaiting a
// Coordinator/In-Charge to assign one via the "Staff" approval screen.
class StaffModel
{
    /** Find a staff row by login email. */
    public function findByEmail(string $email)
    {
        $pdo = Database::getConnection();
        $stmt = $pdo->prepare("SELECT * FROM staff WHERE email = :email LIMIT 1");
        $stmt->execute(['email' => $email]);
        return $stmt->fetch(PDO::FETCH_ASSOC);
    }

    /** Find a staff row by its badge code. */
    public function findByCode(string $code)
    {
        $pdo = Database::getConnection();
        $stmt = $pdo->prepare("SELECT * FROM staff WHERE code = :code LIMIT 1");
        $stmt->execute(['code' => $code]);
        return $stmt->fetch(PDO::FETCH_ASSOC);
    }

    /**
     * Create a new (pending) staff login. The public signup form only
     * collects email/password — no name/phone/role/rank yet. `name` is
     * derived as a placeholder (the column is NOT NULL); the member fills
     * in their real name/phone from Settings once signed in, and a
     * Coordinator assigns a role later (see approve()).
     *
     * @return bool True on success, false on failure
     */
    public function create(string $email, string $password): bool
    {
        $pdo = Database::getConnection();
        $hashedPassword = password_hash($password, PASSWORD_DEFAULT);
        $localPart = strstr($email, '@', true) ?: $email;
        $name = ucwords(str_replace(['.', '_', '-'], ' ', $localPart));
        $code = $this->generateUniqueCode($localPart);

        $stmt = $pdo->prepare(
            "INSERT INTO staff (code, email, password, name, role, academic_rank, position, status)
             VALUES (:code, :email, :password, :name, NULL, NULL, NULL, 'pending')"
        );
        return $stmt->execute([
            'code' => $code,
            'email' => $email,
            'password' => $hashedPassword,
            'name' => $name,
        ]);
    }

    /**
     * Create an ACTIVE academic-staff account on a Coordinator's/In-Charge's
     * behalf (the "Add staff" button). Only the email and rank are known, so:
     *   - `name` is derived from the email, as in create(); the member
     *     corrects it from Settings;
     *   - $temporaryPassword is generated by the caller and sent to the
     *     member, who signs in with it and changes it from Settings → Password.
     *
     * @return array|null ['code' => ..., 'name' => ...], or null on failure
     */
    public function createByAdmin(string $email, string $academicRank, string $temporaryPassword): ?array
    {
        $pdo = Database::getConnection();
        $localPart = strstr($email, '@', true) ?: $email;
        $name = ucwords(str_replace(['.', '_', '-'], ' ', $localPart));
        $code = $this->generateUniqueCode($localPart);

        $stmt = $pdo->prepare(
            "INSERT INTO staff (code, email, password, name, role, academic_rank, position, status)
             VALUES (:code, :email, :password, :name, 'academic_staff', :rank, NULL, 'active')"
        );
        $ok = $stmt->execute([
            'code' => $code,
            'email' => $email,
            'password' => password_hash($temporaryPassword, PASSWORD_DEFAULT),
            'name' => $name,
            'rank' => $academicRank,
        ]);
        return $ok ? ['code' => $code, 'name' => $name] : null;
    }

    /** Update a staff member's password by email. */
    public function updatePassword(string $email, string $newPassword): bool
    {
        $pdo = Database::getConnection();
        $hashedPassword = password_hash($newPassword, PASSWORD_DEFAULT);

        $stmt = $pdo->prepare("UPDATE staff SET password = :password WHERE email = :email");
        return $stmt->execute([
            'email' => $email,
            'password' => $hashedPassword,
        ]);
    }

    /**
     * Self-service profile update: a signed-in member may only change these
     * columns about themselves (not role/rank/position/department/
     * designation/email/etc — those are assigned by a Coordinator/In-Charge
     * via approve()/reassignPosition()/handOverTimetableOfficer()). The
     * array_intersect_key is the actual enforcement, independent of
     * whatever the calling controller trusts from the request body.
     */
    public function updateProfile(string $code, array $fields): bool
    {
        $editable = ['name', 'phone', 'office', 'extension', 'bio'];
        $data = array_intersect_key($fields, array_flip($editable));
        if (empty($data)) {
            return false;
        }

        $pdo = Database::getConnection();
        $set = implode(', ', array_map(fn($col) => "{$col} = :{$col}", array_keys($data)));
        $stmt = $pdo->prepare("UPDATE staff SET {$set} WHERE code = :code");
        return $stmt->execute($data + ['code' => $code]);
    }

    /** Every staff member, most recent first. */
    public function getAllUsers(): array
    {
        $pdo = Database::getConnection();
        $stmt = $pdo->query("SELECT code, email, created_at FROM staff ORDER BY created_at DESC");
        return $stmt->fetchAll(PDO::FETCH_ASSOC);
    }

    /** Signups awaiting a Coordinator/In-Charge to assign a role, oldest first. */
    public function pendingRegistrations(): array
    {
        $pdo = Database::getConnection();
        return $pdo->query(
            "SELECT code, name, email, phone, created_at
             FROM staff WHERE status = 'pending' ORDER BY created_at ASC"
        )->fetchAll(PDO::FETCH_ASSOC);
    }

    /** Every registered staff member (with assigned role), optionally filtered by role/rank/position label. */
    public function activeStaff(?string $roleFilter = null): array
    {
        $pdo = Database::getConnection();
        $sql = "SELECT s.code, s.name, s.email, s.phone, s.role, s.academic_rank, s.position,
                       s.department, s.designation, s.availability_status, s.status,
                       GROUP_CONCAT(DISTINCT cs.course_code ORDER BY cs.course_code SEPARATOR ',') AS assigned_courses
                FROM staff s
                LEFT JOIN course_staff cs ON cs.staff_code = s.code
                WHERE s.role IS NOT NULL";
        $params = [];

        if ($roleFilter === 'timetable_officer') {
            $sql .= " AND s.role = 'timetable_officer'";
        } elseif ($roleFilter === 'junior') {
            $sql .= " AND s.role = 'academic_staff' AND s.academic_rank = 'junior'";
        } elseif ($roleFilter === 'senior') {
            $sql .= " AND s.role = 'academic_staff' AND s.academic_rank = 'senior'";
        }

        $sql .= " GROUP BY s.code ORDER BY s.name";
        $stmt = $pdo->prepare($sql);
        $stmt->execute($params);
        $rows = $stmt->fetchAll(PDO::FETCH_ASSOC);
        $history = $this->codesWithHistory();
        foreach ($rows as &$row) {
            $row['courses'] = !empty($row['assigned_courses']) ? explode(',', $row['assigned_courses']) : [];
            $row['has_history'] = isset($history[$row['code']]);
        }
        return $rows;
    }

    /**
     * Every (table, column) with a foreign key to staff.code, read from the
     * schema rather than listed by hand, so a table added later counts as
     * history without anyone remembering to update this file.
     *   [['leave_requests', 'requester_code'], ['messages', 'sender_code'], ...]
     */
    private function staffReferences(): array
    {
        static $refs = null;   // the schema does not change within a request
        if ($refs === null) {
            $refs = Database::getConnection()->query(
                "SELECT TABLE_NAME, COLUMN_NAME
                 FROM information_schema.KEY_COLUMN_USAGE
                 WHERE TABLE_SCHEMA = DATABASE()
                   AND REFERENCED_TABLE_NAME = 'staff' AND REFERENCED_COLUMN_NAME = 'code'"
            )->fetchAll(PDO::FETCH_NUM);
        }
        return $refs;
    }

    /**
     * Staff codes referenced anywhere — leave, messages, course assignments,
     * notifications, sessions they manage… — as code => true. An account
     * NOT in here has no history and may be deleted outright.
     */
    public function codesWithHistory(): array
    {
        $selects = array_map(
            fn($r) => "SELECT `{$r[1]}` FROM `{$r[0]}` WHERE `{$r[1]}` IS NOT NULL",
            $this->staffReferences()
        );
        if (!$selects) {
            return [];
        }
        $codes = Database::getConnection()->query(implode(' UNION ', $selects))->fetchAll(PDO::FETCH_COLUMN);
        return array_fill_keys($codes, true);
    }

    /** True if anything anywhere references this staff member (see codesWithHistory()). */
    public function hasHistory(string $code): bool
    {
        $refs = $this->staffReferences();
        if (!$refs) {
            return false;
        }
        $exists = [];
        $params = [];
        foreach ($refs as $i => [$table, $column]) {
            $exists[] = "EXISTS (SELECT 1 FROM `{$table}` WHERE `{$column}` = :c{$i})";
            $params["c{$i}"] = $code;
        }
        $stmt = Database::getConnection()->prepare('SELECT ' . implode(' OR ', $exists));
        $stmt->execute($params);
        return (bool) $stmt->fetchColumn();
    }

    /**
     * Hard-delete an account that has no history. False if it has any, or is
     * already gone. The row is locked first: InnoDB makes every INSERT that
     * references it (a leave request, a message…) wait on that lock for its
     * foreign-key check, so nothing can be linked to the account between the
     * hasHistory() check and the DELETE — which would otherwise cascade it away.
     */
    public function deleteIfNoHistory(string $code): bool
    {
        $pdo = Database::getConnection();
        $pdo->beginTransaction();
        try {
            $lock = $pdo->prepare("SELECT 1 FROM staff WHERE code = :code FOR UPDATE");
            $lock->execute(['code' => $code]);
            if (!$lock->fetchColumn() || $this->hasHistory($code)) {
                $pdo->rollBack();
                return false;
            }
            $delete = $pdo->prepare("DELETE FROM staff WHERE code = :code");
            $delete->execute(['code' => $code]);
            $pdo->commit();
            return $delete->rowCount() === 1;
        } catch (\Throwable $e) {
            $pdo->rollBack();
            return false;
        }
    }

    /**
     * Approve a pending registration: assigns role/rank and activates the
     * account. `$academicRank` is required (and only meaningful) when
     * `$role === 'academic_staff'`.
     */
    public function approve(string $code, string $role, ?string $academicRank): bool
    {
        $pdo = Database::getConnection();
        $stmt = $pdo->prepare(
            "UPDATE staff
             SET role = :role, academic_rank = :academic_rank, status = 'active'
             WHERE code = :code AND status = 'pending'"
        );
        return $stmt->execute([
            'role' => $role,
            'academic_rank' => $role === 'academic_staff' ? $academicRank : null,
            'code' => $code,
        ]) && $stmt->rowCount() > 0;
    }

    /** Reject (discard) a pending registration. */
    public function reject(string $code): bool
    {
        $pdo = Database::getConnection();
        $stmt = $pdo->prepare("DELETE FROM staff WHERE code = :code AND status = 'pending'");
        return $stmt->execute(['code' => $code]) && $stmt->rowCount() > 0;
    }

    /**
     * Deactivate a member who has left the university. The row is kept so
     * every history screen still resolves their name (see migration 023);
     * login refuses them from now on. Their course assignments are removed
     * in the same transaction — course_staff holds who teaches a course NOW,
     * not who taught it — so they stop showing in the course/timetable
     * pickers, and the officer reassigns those courses.
     *
     * The WHERE clause is the eligibility rule: active academic staff with no
     * coordinator/in-charge seat. The caller explains any refusal first.
     */
    public function deactivate(string $code, string $byCode): bool
    {
        $pdo = Database::getConnection();
        $pdo->beginTransaction();
        try {
            $stmt = $pdo->prepare(
                "UPDATE staff
                    SET status = 'inactive', deactivated_at = NOW(), deactivated_by = :by
                  WHERE code = :code AND status = 'active'
                    AND role = 'academic_staff' AND position IS NULL"
            );
            $stmt->execute(['code' => $code, 'by' => $byCode]);
            if ($stmt->rowCount() !== 1) {
                $pdo->rollBack();
                return false;
            }
            $pdo->prepare("DELETE FROM course_staff WHERE staff_code = :code")->execute(['code' => $code]);
            $pdo->commit();
            return true;
        } catch (\Throwable $e) {
            $pdo->rollBack();
            return false;
        }
    }

    /** Course codes this member is currently assigned to, e.g. ['CS2201', 'CS3105']. */
    public function courseCodes(string $code): array
    {
        $pdo = Database::getConnection();
        $stmt = $pdo->prepare("SELECT course_code FROM course_staff WHERE staff_code = :code ORDER BY course_code");
        $stmt->execute(['code' => $code]);
        return $stmt->fetchAll(PDO::FETCH_COLUMN);
    }

    /** Undo deactivate(). Course assignments are not restored — the officer reassigns them. */
    public function reactivate(string $code): bool
    {
        $pdo = Database::getConnection();
        $stmt = $pdo->prepare(
            "UPDATE staff SET status = 'active', deactivated_at = NULL, deactivated_by = NULL
             WHERE code = :code AND status = 'inactive'"
        );
        return $stmt->execute(['code' => $code]) && $stmt->rowCount() > 0;
    }

    /**
     * The current holders of the three "key role" seats managed from the
     * In-Charge "Accounts" screen: the timetable officer, and every active
     * coordinator/in-charge. Used to render the Role Assignment table.
     */
    public function roleHolders(): array
    {
        $pdo = Database::getConnection();
        return $pdo->query(
            "SELECT code, name, email, role, academic_rank, position
             FROM staff
             WHERE status = 'active' AND (role = 'timetable_officer' OR position IN ('coordinator', 'in_charge'))
             ORDER BY FIELD(position, 'in_charge', 'coordinator') , role DESC, name"
        )->fetchAll(PDO::FETCH_ASSOC);
    }

    /** Active academic staff of a given rank, for the "search lecturer" replacement picker. */
    public function activeByRank(string $academicRank): array
    {
        $pdo = Database::getConnection();
        $stmt = $pdo->prepare(
            "SELECT code, name, email, academic_rank, position
             FROM staff
             WHERE status = 'active' AND role = 'academic_staff' AND academic_rank = :rank
             ORDER BY name"
        );
        $stmt->execute(['rank' => $academicRank]);
        return $stmt->fetchAll(PDO::FETCH_ASSOC);
    }

    /**
     * Reassign the `position` seat (coordinator/in_charge) from one staff
     * member to another. The caller must have already validated that
     * `$toCode` holds the matching `academic_rank` (coordinator -> junior,
     * in_charge -> senior) — the DB CHECK constraint enforces it either way.
     */
    public function reassignPosition(string $fromCode, string $toCode, string $position): bool
    {
        $pdo = Database::getConnection();
        $pdo->beginTransaction();
        try {
            $clear = $pdo->prepare("UPDATE staff SET position = NULL WHERE code = :code AND position = :position");
            $clear->execute(['code' => $fromCode, 'position' => $position]);

            $set = $pdo->prepare("UPDATE staff SET position = :position WHERE code = :code");
            $set->execute(['position' => $position, 'code' => $toCode]);

            $pdo->commit();
            return true;
        } catch (\Throwable $e) {
            $pdo->rollBack();
            return false;
        }
    }

    /** How many active staff hold a `position` seat (coordinator / in_charge). */
    public function countByPosition(string $position): int
    {
        $pdo = Database::getConnection();
        $stmt = $pdo->prepare("SELECT COUNT(*) FROM staff WHERE status = 'active' AND position = :position");
        $stmt->execute(['position' => $position]);
        return (int)$stmt->fetchColumn();
    }

    /**
     * Give an ADDITIONAL `position` seat to someone who holds none — the
     * In-Charge's "Add coordinator", where nobody is being replaced. The WHERE
     * clause is the eligibility rule (active academic staff of the matching
     * rank, no seat yet), so a stale or forged code simply updates nothing.
     */
    public function assignPosition(string $code, string $position): bool
    {
        $rank = $position === 'coordinator' ? 'junior' : 'senior';
        $pdo = Database::getConnection();
        $stmt = $pdo->prepare(
            "UPDATE staff SET position = :position
             WHERE code = :code AND status = 'active' AND role = 'academic_staff'
               AND academic_rank = :rank AND position IS NULL"
        );
        return $stmt->execute(['position' => $position, 'code' => $code, 'rank' => $rank])
            && $stmt->rowCount() > 0;
    }

    /** Take a `position` seat away; the member stays on staff at their rank. */
    public function revokePosition(string $code, string $position): bool
    {
        $pdo = Database::getConnection();
        $stmt = $pdo->prepare("UPDATE staff SET position = NULL WHERE code = :code AND position = :position");
        return $stmt->execute(['code' => $code, 'position' => $position]) && $stmt->rowCount() > 0;
    }

    /**
     * Hand the Timetable Officer account to a new person. The row — and its
     * code, so every session, notification and record it owns — stays; only
     * the login changes. The password becomes unusable, so the new officer
     * sets their own with Forgot password, and the previous officer's
     * personal details are cleared for the new one to fill in from Settings.
     * Changing the email also signs the previous officer out (see
     * Controller::sessionStillValid()).
     *
     * False if $code is not the officer's account or the email was taken
     * in the meantime (UNIQUE).
     */
    public function handOverTimetableOfficer(string $code, string $newEmail): bool
    {
        $pdo = Database::getConnection();
        $stmt = $pdo->prepare(
            "UPDATE staff
                SET email = :email, password = :password, name = 'Timetable Officer',
                    phone = NULL, office = NULL, extension = NULL, bio = NULL
              WHERE code = :code AND role = 'timetable_officer'"
        );
        try {
            $stmt->execute([
                'email'    => $newEmail,
                'password' => password_hash(bin2hex(random_bytes(32)), PASSWORD_DEFAULT),
                'code'     => $code,
            ]);
        } catch (\PDOException $e) {
            return false;
        }
        return $stmt->rowCount() === 1;
    }

    /** A short, unique badge code derived from an email's local part. */
    private function generateUniqueCode(string $localPart): string
    {
        $pdo = Database::getConnection();
        $base = strtoupper(preg_replace('/[^A-Za-z]/', '', $localPart));
        $base = substr($base !== '' ? $base : 'STF', 0, 3);

        $stmt = $pdo->prepare("SELECT 1 FROM staff WHERE code = :code");
        $code = $base;
        $suffix = 1;
        while (true) {
            $stmt->execute(['code' => $code]);
            if (!$stmt->fetch()) {
                return $code;
            }
            $code = $base . $suffix;
            $suffix++;
        }
    }
}
